repos:
  - repo: local
    hooks:
      - id: ruff-lint
        name: ruff lint
        entry: ruff
        language: system
        types: [python]
        args: ["check", "--fix", "--exit-non-zero-on-fix"]
      - id: ruff-format
        name: ruff format
        entry: ruff
        language: system
        types: [python]
        args: ["format"]