FROM python:3.9-slim

COPY requirements.txt /app/requirements.txt
COPY src /app/src
WORKDIR /app

EXPOSE 8501

RUN pip install -r requirements.txt

CMD ["streamlit", "run", "main_page.py", "--server.port=8501", "--server.address=0.0.0.0"]
